username: 'mailbot@example.com'
password: 'super secret smtp password'
smtp_server: 'smtp.example.com'
smtp_port: 587 
alert_address: 'oncall@example.com'
client_log_dir: '/var/log/netmonitor'
down_interval:  # This is passes as arguments to datetime.timedelta()
        minutes: 3
